---
version: '2'

services:
  db:
    image: mariadb:10
    ports:
      - 127.0.0.1:3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: director
      MYSQL_USER: director
      MYSQL_PASSWORD: director
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
